language: elixir
os: linux
dist: jammy
services:
  - docker
otp_release:
  - 26.1.1
elixir:
  - 1.15.7

jobs:
  include:
    - arch: arm64-graviton2
      dist: jammy
      virt: vm
      group: stable
      install:
        - kiex use 1.15.7
        - mix local.hex --force
        - mix local.rebar --force
        - git config --global url.https://github.com/.insteadOf git://github.com/
        - git config --global url.ssh://git@github.com/GameAnalytics/.insteadOf https://github.com/GameAnalytics/
        - chmod +x ci-scripts/notify_after_failure.sh
      script:
        - ./ci-scripts/install_ddev.sh
        - mix deps.get
        - MIX_ENV=live mix compile
        - MIX_ENV=live mix release --overwrite
        - sudo chown -R travis:travis _build deps
        - mv -v _build/live/splitfire-*.tar.gz ./splitfire-${TRAVIS_CPU_ARCH}.tar.gz
      after_failure:
        - ./ci-scripts/notify_after_failure.sh
      deploy:
        # your deployment configurations...

# Add your deployment configuration here...
